// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

package builtin

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/vmihailenco/msgpack"
)

func Test_PoolOfFloat32(t *testing.T) {
	arr := NewPoolOfFloat32()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfFloat32{}.data).Elem(), arr.Type())

	index1 := arr.Add(float32(123))
	index2 := arr.Add(float32(123))

	{
		count := 0
		arr.View(func(_ *float32) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, float32(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *float32) {
		*v = 888
	})
	assert.Equal(t, float32(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *float32) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfFloat32(t *testing.T) {
	original := NewPoolOfFloat32()
	decoded := NewPoolOfFloat32()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfFloat64(t *testing.T) {
	arr := NewPoolOfFloat64()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfFloat64{}.data).Elem(), arr.Type())

	index1 := arr.Add(float64(123))
	index2 := arr.Add(float64(123))

	{
		count := 0
		arr.View(func(_ *float64) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, float64(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *float64) {
		*v = 888
	})
	assert.Equal(t, float64(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *float64) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfFloat64(t *testing.T) {
	original := NewPoolOfFloat64()
	decoded := NewPoolOfFloat64()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfInt16(t *testing.T) {
	arr := NewPoolOfInt16()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfInt16{}.data).Elem(), arr.Type())

	index1 := arr.Add(int16(123))
	index2 := arr.Add(int16(123))

	{
		count := 0
		arr.View(func(_ *int16) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, int16(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *int16) {
		*v = 888
	})
	assert.Equal(t, int16(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *int16) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfInt16(t *testing.T) {
	original := NewPoolOfInt16()
	decoded := NewPoolOfInt16()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfInt32(t *testing.T) {
	arr := NewPoolOfInt32()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfInt32{}.data).Elem(), arr.Type())

	index1 := arr.Add(int32(123))
	index2 := arr.Add(int32(123))

	{
		count := 0
		arr.View(func(_ *int32) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, int32(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *int32) {
		*v = 888
	})
	assert.Equal(t, int32(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *int32) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfInt32(t *testing.T) {
	original := NewPoolOfInt32()
	decoded := NewPoolOfInt32()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfInt64(t *testing.T) {
	arr := NewPoolOfInt64()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfInt64{}.data).Elem(), arr.Type())

	index1 := arr.Add(int64(123))
	index2 := arr.Add(int64(123))

	{
		count := 0
		arr.View(func(_ *int64) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, int64(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *int64) {
		*v = 888
	})
	assert.Equal(t, int64(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *int64) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfInt64(t *testing.T) {
	original := NewPoolOfInt64()
	decoded := NewPoolOfInt64()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfUint16(t *testing.T) {
	arr := NewPoolOfUint16()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfUint16{}.data).Elem(), arr.Type())

	index1 := arr.Add(uint16(123))
	index2 := arr.Add(uint16(123))

	{
		count := 0
		arr.View(func(_ *uint16) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, uint16(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *uint16) {
		*v = 888
	})
	assert.Equal(t, uint16(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *uint16) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfUint16(t *testing.T) {
	original := NewPoolOfUint16()
	decoded := NewPoolOfUint16()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfUint32(t *testing.T) {
	arr := NewPoolOfUint32()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfUint32{}.data).Elem(), arr.Type())

	index1 := arr.Add(uint32(123))
	index2 := arr.Add(uint32(123))

	{
		count := 0
		arr.View(func(_ *uint32) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, uint32(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *uint32) {
		*v = 888
	})
	assert.Equal(t, uint32(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *uint32) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfUint32(t *testing.T) {
	original := NewPoolOfUint32()
	decoded := NewPoolOfUint32()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}

// Copyright (c) Roman Atachiants and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

func Test_PoolOfUint64(t *testing.T) {
	arr := NewPoolOfUint64()
	assert.NotNil(t, arr)
	assert.Equal(t, reflect.TypeOf(pageOfUint64{}.data).Elem(), arr.Type())

	index1 := arr.Add(uint64(123))
	index2 := arr.Add(uint64(123))

	{
		count := 0
		arr.View(func(_ *uint64) {
			count++
		})
		assert.Equal(t, 2, count)
	}

	assert.Equal(t, uint64(123), arr.ViewAt(index1))
	arr.UpdateAt(index2, func(v *uint64) {
		*v = 888
	})
	assert.Equal(t, uint64(888), arr.ViewAt(index2))

	arr.RemoveAt(index1)
	arr.RemoveAt(index2)

	{
		count := 0
		arr.Update(func(_ *uint64) {
			count++
		})
		assert.Equal(t, 0, count)
	}
}

func Test_CodecOfUint64(t *testing.T) {
	original := NewPoolOfUint64()
	decoded := NewPoolOfUint64()

	// Encode the buffer
	var encoded bytes.Buffer
	err := msgpack.NewEncoder(&encoded).Encode(original)

	// Decode from the buffer
	dec := msgpack.NewDecoder(bytes.NewBuffer(encoded.Bytes()))
	err = dec.Decode(decoded)
	assert.NoError(t, err)
	assert.Equal(t, original, decoded)
}
